<?php

namespace Tests\Unit\Controller;

use App\Http\Controllers\ProductController;
use App\Services\ProductService;
use PHPUnit\Framework\TestCase;

class ProductControllerTest extends TestCase
{
    protected $productController;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $productService = $this->getMockBuilder(ProductService::class)
                                ->getMock();
        $productService->expects($this->any())->method('getAllProducts')->will($this->returnValue([

        ]));
        $this->productController = new ProductController($productService);

    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testGetProducts()
    {

        $this->productController->index();
        $this->assertTrue(true);
    }
}
